# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "tiffany.blog"
description: "your friend tiffany's little corner of the internet"
baseurl: # baseurl
url: https://tiffanywhite.blog
logo: https://res.cloudinary.com/thatmacnerd/image/upload/v1565224506/twhiteblog-avi.png
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Fira Sans"
    weights: "400,400i,700,700i"
  - name: "Bitter"
    weights: "400,400i,700,700i"
  - name: "PT Sans"
    weights: "400,400i,700,700i"
google_analytics: UA-158913183-1
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: twhiteblog

collections:
  homescreens:
    output: true
    permalink: /:collection/:path/
  headphones:
    output: true
    permalink: /:collection/:path/
  bags:
    output: true
    permalink: /:collection/:path/
  fitness:
    output: true
    permalink: /:collection/:path/


# Liquid
liquid:
  error_mode: strict
future: false
pwa:
  sw_src_filepath: sw.js # Optional
  sw_dest_filename: sw.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - "fonts/**/*"

# Build settings
permalink: /:year/:month/:day/:title/
markdown: kramdown

feed:
  path: atom.xml
  categories:
    - App Review
    - iOS Automation
    - Pick of the month
    - Linked Post
  collections:
    - headphones
    - homescreens
    - bags
    - fitness

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-json-feed

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  - scope:
      path: "_homescreens"
      type: homescreens
    values:
      layout: post
      comments: false
      share: true
  - scope:
      path: "_headphones"
      type: headphones
    values:
      layout: post
      comments: false
      share: true
  - scope:
      path: "_bags"
      type: bags
    values:
      layout: post
      comments: false
      share: true
  - scope:
      path: "_fitness"
      type: fitness
    values:
      layout: post
      comments: false
      share: true

# Site Author
author:
  name: Tiffany White
  picture: https://res.cloudinary.com/thatmacnerd/image/upload/v1565224506/twhiteblog-avi.png
  email:
  twitter: twhiteblog
  links:
    - title: Instagram
      url: https://www.instagram.com/trwhitephoto
      icon: fab fa-instagram
    - title: Apple Music
      url: https://music.apple.com/profile/tiffanywhitedev
      icon: fab fa-itunes
    - title: YouTube
      url: https://www.youtube.com/channel/UC9qGqkUI94P3UxP3-TwibbA
      icon: fab fa-youtube
# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/twhiteblog
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://www.instagram.com/trwhitephoto
    icon: fab fa-instagram
  - title: Apple Music
    url: https://music.apple.com/profile/tiffanywhitedev
    icon: fab fa-itunes
  - title: Vimeo
    url: https://vimeo.com/tiffanywhite
    icon: fab fa-vimeo-square
  - title: RSS Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: JSON Feed
    url: feed.json
    icon: fas fa-code
  - title: Status
    url: https://status.tiffanywhite.blog
    icon: fas fa-file-medical-alt
